# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'livereload', :port => '35728' do
  watch(%r{app/views/.+\.(html|erb|haml|slim)})
  watch(%r{app/helpers/.+\.rb})
  watch(%r{public/.+\.(css|js|html)})
  watch(%r{config/locales/.+\.yml})
  # Rails Assets Pipeline
  watch(%r{(app|vendor)/assets/\w+/(.+\.(css|js|html)).*})  { |m| "/assets/#{m[2]}" }
  watch(%r{app/client/lib/partials/.+})
end
