namespace :test do
  desc 'run the tests'
  task :run do
    command = "java " \
      "-jar development/JsTestDriver.jar " \
      "--config development/jsTestDriver.conf " \
      "--basePath #{File.expand_path('../../', __FILE__)} " \
      "--tests all " \
      "--reset"
    puts command
    system(command)
  end

  desc 'run the jsTestDriverServer'
  task :server do
    puts 'Starting JsTestDirver Server'
    command = "java " \
      "-jar development/JsTestDriver.jar " \
      "--config development/jsTestDriver.conf " \
      "--port 9877 " \
      "--browser open " \
      "--basePath #{File.expand_path('../../', __FILE__)}"
    puts command
    system(command)
  end

  desc 'run the jsTestDriverServer for unit tests'
  task :unit_server do
    puts 'Starting unit test server'
    command = "java " \
      "-jar development/JsTestDriver2.jar " \
      "--config development/jsTestDriverUnit.conf " \
      "--port 10000 " \
      "--basePath #{File.expand_path('../../', __FILE__)}"
    puts command
    system(command)
  end
  
  desc 'run the unit tests'
  task :unit_run do
    command = "java " \
      "-jar development/JsTestDriver2.jar " \
      "--config development/jsTestDriverUnit.conf " \
      "--basePath #{File.expand_path('../../', __FILE__)} " \
      "--tests all "
    puts command
    system(command)
  end

end


